 # theme: jekyll-theme-slate
title: Sreeharsha Udayashankar
description: Welcome to my personal page!
linkedin_url: https://www.linkedin.com/in/sreeharshau/
resume_url: /Sreeharsha_Resume_2022.pdf

markdown: GFM
plugins:
  - jekyll-remote-theme
   - jekyll-include-cache
   
gtag: G-9RQMH51FDR

remote_theme: daattali/beautiful-jekyll
