# theme: jekyll-theme-slate
remote_theme: amitmerchant1990/reverie
title: Sreeharsha Udayashankar
description: Welcome to my personal page!
markdown: GFM
plugins:
  - jekyll-seo-tag
google_analytics: UA-181067473-1
