 # theme: jekyll-theme-slate
title: Sreeharsha Udayashankar
description: Welcome to my personal page!
linkedin_url: https://www.linkedin.com/in/sreeharshau/
markdown: GFM
plugins:
  - jekyll-remote-theme
google_analytics: UA-181067473-1

remote_theme: pages-themes/dinky@v0.2.0
