 # theme: jekyll-theme-slate
title: Sreeharsha Udayashankar
description: Welcome to my personal page!
linkedin_url: https://www.linkedin.com/in/sreeharshau/
resume_url: /Sreeharsha_Resume_2022.pdf

markdown: GFM
plugins:
  - jekyll-remote-theme
   - jekyll-include-cache
   
gtag: G-9RQMH51FDR

remote_theme: daattali/beautiful-jekyll

avatar: "/images/avatar.png"
round-avatar: true

navbar-links:
  Resume: "/Sreeharsha_Resume_2022.pdf"
  LinkedIn: "https://www.linkedin.com/in/sreeharshau/"
  GitHub: "https://github.com/sreeharshau"

social-network-links:
  email: "sreeharsha6196@gmail.com"
  google-scholar: "https://scholar.google.com/citations?user=6WkIqjkAAAAJ&hl=en"
  linkedin: "https://www.linkedin.com/in/sreeharshau/"
  github: sreeharshau
 

