 # theme: jekyll-theme-slate
title: Sreeharsha Udayashankar
description: 
linkedin_url: https://www.linkedin.com/in/sreeharshau/
resume_url: /Sreeharsha_Resume_2022.pdf

markdown: GFM
plugins:
  - jekyll-remote-theme
   - jekyll-include-cache
   
gtag: G-9RQMH51FDR

remote_theme: daattali/beautiful-jekyll

navbar-links:
  Resume: "/Sreeharsha_Resume.pdf"
  LinkedIn: "https://www.linkedin.com/in/sreeharshau/"
  Publications: "https://sreeharshau.github.io/publications"
  Side Projects: "https://sreeharshau.github.io/side_projects"
  Hiking: "https://sreeharshau.github.io/hiking"

social-network-links:
  email: "s2udayas@uwaterloo.ca"
  google-scholar: "6WkIqjkAAAAJ"
  linkedin: sreeharshau
  github: sreeharshau
 
css: "/custom_style.css"
